---
- name: Verify
  hosts: all

  tasks:
    - name: collect facts about system services
      ansible.builtin.service_facts:
      register: services_state

    - name: verify Netbox services are running
      assert:
        that: item.state == 'running'
      with_items:
        - "{{ services_state.ansible_facts.services['netbox.service'] }}"
        - "{{ services_state.ansible_facts.services['netbox-rq.service'] }}"
