---
- name: install.redhat | include Amazon Linux 2 tasks
  include_tasks: install.amazon.yml
  when: ansible_distribution == 'Amazon'

- name: install.redhat | install required system packages
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop:
    - gcc
    - git
    - python38
    - python38-devel
    - python3-pip
    - libxml2-devel
    - libxslt-devel
    - libffi-devel
    - libpq-devel
    - openssl-devel
    - redhat-rpm-config

- name: install.redhat | install Git
  ansible.builtin.yum:
    name: git
    state: present
  when: netbox_install_method == 'git'

- name: install.redhat | install system packages for LDAP authentication
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  loop:
    - openldap-devel
  when: netbox_auth_ldap is defined
