---
dependency:
  name: galaxy
  options:
    role-file: molecule/default/requirements.yml

driver:
  name: docker

platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-centos8}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    network_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  playbooks:
    prepare: ../default/prepare.yml
    converge: converge.yml
    verify: ../default/verify.yml
