---
- name: handlers | check Netbox configuration
  ansible.builtin.shell: |
    source {{ netbox_current_path }}/venv/bin/activate
    python3 manage.py check
  args:
    chdir: "{{ netbox_current_path }}/netbox"
    executable: /bin/bash
  become: yes
  become_method: sudo
  become_user: "{{ netbox_user }}"
  listen: restart_netbox
  register: config_check
  failed_when: "config_check.stdout != 'System check identified no issues (0 silenced).'"

- name: handlers | restart Netbox services
  ansible.builtin.service:
    name: "{{ item }}"
    state: restarted
  become: yes
  listen: restart_netbox
  loop:
    - netbox
    - netbox-rq
