---
- name: handlers | plugins | migrate database
  ansible.builtin.shell: |
    source {{ netbox_current_path }}/venv/bin/activate
    python3 manage.py migrate
  args:
    chdir: "{{ netbox_current_path }}/netbox"
    executable: /bin/bash
  become: yes
  become_method: sudo
  become_user: "{{ netbox_user }}"
  register: db_migration
  notify: restart_netbox
  changed_when: "'No migrations to apply.' not in db_migration.stdout"

- name: handlers | plugins | collect static files
  ansible.builtin.shell: |
    source {{ netbox_current_path }}/venv/bin/activate
    python3 manage.py collectstatic --noinput
  args:
    chdir: "{{ netbox_current_path }}/netbox"
    executable: /bin/bash
  become: yes
  become_method: sudo
  become_user: "{{ netbox_user }}"
  register: static_collection
  notify: restart_netbox
  changed_when: "'0 static files copied' not in static_collection.stdout"
