---
- name: Converge
  hosts: all

  vars:
    netbox_version_tag: "{{ lookup('env', 'NETBOX_VERSION_TAG') | default() }}"
    netbox_db_username: netbox
    netbox_db_password: netbox
    netbox_field_choices:
      dcim.Site.status:
        - ['foo', 'Foo', 'red']
        - ['bar', 'Bar', 'green']
        - ['baz', 'Baz', 'blue']
    netbox_napalm:
      username: napalm
      password: testing
      timeout: 30
      args: {}
    netbox_secret_key: "lnvRn_5Bypl8hBV4mMwgsMuHxr6uZvGwJyDqB7fcKqo"
    netbox_superusers:
      - username: admin
        password: admin
        email: changeme@example.com

  roles:
    - role: jvoss.netbox
